import React from "react";

const datos = [
  {
    id: 1,
    nombre: "Maria",
    description:
      "Ha sido de la mejor estadía de nuestras vidas, super recomendable!",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/rachel-mcdermott-0fN7Fxv1eWA-unsplash.jpg",
    pais: "Argentina",
    score: 4.5,
    priceQualityRatio: 5,
    facilities: 4,
    location: 4,
    cleaning: 4,
    attentionService: 5,
    comfortable: 2,
    stayedOn: "JUN/2022",
    isDeleted: false,
    createdAt: "2022-05-11T22:41:48.081Z",
    UserId: 1,
    HotelId: 1,
    BookingId: 1,
  },
  {
    id: 2,
    nombre: "Pedro",
    description:
      "Super recomendable!, Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/joackim-weiler-lxX0dJQHV3w-unsplash.jpg",
    pais: "Colombia",
    score: 4,
    priceQualityRatio: 5,
    facilities: 4,
    location: 4,
    cleaning: 4,
    attentionService: 5,
    comfortable: 5,
    stayedOn: "JUN/2022",
    isDeleted: false,
    createdAt: "2022-05-11T22:41:59.184Z",
    UserId: 2,
    HotelId: 1,
    BookingId: 2,
  },
  {
    id: 4,
    nombre: "Juan",
    description: "Recomendable!",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/reza-biazar-eSjmZW97cH8-unsplash.jpg",
    pais: "Perú",
    score: 4.8444444444444445,
    priceQualityRatio: 4,
    facilities: 4,
    location: 4,
    cleaning: 4,
    attentionService: 5,
    comfortable: 5,
    stayedOn: "JUN/2022",
    isDeleted: false,
    createdAt: "2022-05-21T22:42:25.275Z",
    UserId: 4,
    HotelId: 1,
    BookingId: 4,
  },
  {
    id: 4,
    nombre: "Fernanda",
    description:
      "Lorem ipsum dolor sit amet consectetur adipisicing elit. Ullam nemo voluptas ab, repellat itaque odio, fugiat magni impedit eligendi animi ipsa ipsum nesciunt laborum officia dignissimos ut debitis, maiores quod!",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/manny-moreno-Jm1CwCoYxkM-unsplash.jpg",
    pais: "Chile",
    score: 4.8444444444444445,
    priceQualityRatio: 5,
    facilities: 4,
    location: 4,
    cleaning: 4,
    attentionService: 5,
    comfortable: 4,
    stayedOn: "JUL/2022",
    isDeleted: false,
    createdAt: "2022-05-11T22:42:25.275Z",
    UserId: 1,
    HotelId: 1,
    BookingId: 4,
  },
  {
    id: 5,
    nombre: "Valentina",
    description:
      "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/sam-burriss-jTSf1xnsoCs-unsplash.jpg",
    pais: "Uruguay",
    score: 4.8444444444444445,
    priceQualityRatio: 4,
    facilities: 4,
    location: 5,
    cleaning: 5,
    attentionService: 4,
    comfortable: 4,
    stayedOn: "FEB/2022",
    isDeleted: false,
    createdAt: "2022-01-21T22:42:25.275Z",
    UserId: 4,
    HotelId: 1,
    BookingId: 4,
  },
  {
    id: 6,
    nombre: "Nicolas",
    description:
      "Vivamus eu lectus dapibus, cursus nibh ut, elementum felis. Praesent diam neque, hendrerit pellentesque fermentum eu, pellentesque eget urna. Sed elementum tristique metus, eget auctor massa varius vitae. Duis ultricies nulla at ultricies interdum. Curabitur massa sapien, iaculis nec faucibus in, pharetra id lacus. Aenean in cursus ligula. Maecenas sollicitudin justo eu pulvinar bibendum. Mauris molestie, sapien id dapibus gravida, orci risus fermentum ante, vitae elementum metus massa a felis. Aliquam ut purus eu est feugiat feugiat dignissim nec tortor. Proin ullamcorper libero non nunc cursus fermentum.",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/meysam-jarahkar-l4gz33evF9k-unsplash.jpg",
    // image: "https://api.lorem.space/image/face",  // no eliminar
    pais: "Paraguay",
    score: 4.8444444444444445,
    priceQualityRatio: 4,
    facilities: 4,
    location: 4,
    cleaning: 4,
    attentionService: 4,
    comfortable: 4,
    stayedOn: "APR/2022",
    isDeleted: false,
    createdAt: "2022-02-19T22:42:25.275Z",
    UserId: 5,
    HotelId: 1,
    BookingId: 4,
  },
  {
    id: 6,
    nombre: "Jesus",
    description:
      "Vivamus eu lectus dapibus, cursus nibh ut, elementum felis. Praesent diam neque, hendrerit pellentesque fermentum eu, pellentesque eget urna. Sed elementum tristique metus, eget auctor massa varius vitae. Duis ultricies nulla at ultricies interdum. Curabitur massa sapien, iaculis nec faucibus in, pharetra id lacus. Aenean in cursus ligula. Maecenas sollicitudin justo eu pulvinar bibendum. Mauris molestie, sapien id dapibus gravida, orci risus fermentum ante, vitae elementum metus massa a felis.",
    image:
      "https://cdn.lorem.space/images/face/.cache/500x0/nico-marks-25gAg2MOXxQ-unsplash.jpg",
    // image: "https://api.lorem.space/image/face",  // no eliminar
    pais: "Paraguay",
    score: 4.8444444444444445,
    priceQualityRatio: 4,
    facilities: 4,
    location: 4,
    cleaning: 4,
    attentionService: 4,
    comfortable: 4,
    stayedOn: "APR/2022",
    isDeleted: false,
    createdAt: "2022-02-19T22:42:25.275Z",
    UserId: 5,
    HotelId: 1,
    BookingId: 4,
  },
];

export default datos;
